### ISSUE TITLE
Try to decode a google map with Chinese data and seems not able to deal with UNICODE data

### ISSUE THREAD

**Issue by kwccoin** [johnwesonga/kmlparser#2]
One example is this: https://www.google.com/maps/d/u/0/viewer?mid=18DPgYjcBCtRWAcmYKdOi2X593P4&hl=en_US

I download the .kml file and I got a problem as here

```
Traceback (most recent call last):
  File "kmlparser.py", line 123, in <module>
    main()
  File "kmlparser.py", line 120, in main
    upload_file = kmlparser.WriteCsv()
  File "kmlparser.py", line 67, in WriteCsv
    writer.writerow(row)
  File "...csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordin
al not in range(128)
```

I am not sure it is yours or it is the csv.py issue though.

For your kind advice.

**Comment by johnwesonga** [comment]
A simple fix is to UTF-8 encode the  locationdata['name'] = text.encode('utf-8'), which seems to do solve the problem.

**Comment by johnwesonga** [comment]
A simple fix is to UTF-8 encode the  locationdata['name'] = text.encode('utf-8'), which seems to do solve the problem.
